services:
  mssql:
    restart: always
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Alexandra2024!
      - MSSQL_PID=Evaluation
    ports:
      - "1433:1433"
    volumes:
      - ./docker/mssql:/var/opt/mssql/data